name: hw1_env
dependencies:
    - python=3.10.10
    - pip
    - pip:
        - numpy==1.22.4
        - pandas==1.5.3
        - pandas-datareader==0.10.0
        - pandas-gbq==0.17.9
        - matplotlib==3.7.1
        - matplotlib-inline==0.1.6
        - matplotlib-venn==0.11.9
        - joblib==1.2.0
        - sklearn-pandas==2.2.0